### ISSUE TITLE
A comment for 2nd assignment

### ISSUE THREAD

**Issue by CatalinaDonic** [karinvar/karinvar.github.io#2]
Hi Karin,

I really like the aesthetics of your website!

I noticed that the text under your picture, "Hosted on GitHub Pages — Theme by [orderedlist](https://github.com/orderedlist)," appears layered, with one line overlapping the other. Perhaps adjusting the layout so each line appears separately could make it clearer.

Hope it's an easy fix!
Best,
Catalina

@HadarKlimovski

**Comment by karinvar** [comment]
Hi Catalina, I don't think I understood the issue, it seems to me that it is in one line (attached a screenshot):
<img width="352" alt="image" src="https://github.com/user-attachments/assets/761699f8-62d6-4153-a910-3776df7e89ff">
 
Please let me know if I understood wrongly, and I'll fix it.
Thanks,
Karin

**Comment by CatalinaDonic** [comment]
Oh, for me it looks like this:
<img width="259" alt="Screenshot" src="https://github.com/user-attachments/assets/c6875cc2-7608-418a-a213-572cf9cd6711">
But if you don't see it, it might be only my browser, and then I guess it can't be fixed.

Best,
Catalina

**Comment by HadarKlimovski** [comment]
@CatalinaDonic +1
